name: Angular CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup Node
      run: |
        cd ./intechnet-pupils/
        npm install
        npm update

    - name: Setup Angular
      run: |
        npm install @angular/cli
        npm install @angular-devkit/schematics
 
    - name: Build project   
      run: |
        npm run build:ci
